# @todo ajouter une option au cli --config-file (-c) qui permet de
#   définir le fichier de configuration à utiliser. Par défaut on
#   utilise un fichier nommé ./a12s-drupal-compiler.yml
# @todo À partir du fichier de config, on détermine la racine du
#   projet. Renommer la variable drupalRoot par rootFolder.
# @todo simplifier le système de configuration parce qu'on aura
#   seulement un projet à la fois.
# @todo Ajouter une commande de gulp qui va se charger de copier
#   les librairies node_modules vers le chemin dans assets/vendor.
drupalRoot: "./"

# Icon font
#
# https://github.com/nfroidure/gulp-iconfont
icons:
  enabled: false
  fontPathPrefix: "../font-icon/"
  classNamePrefix: "fi" # Font Icons
  autohint: false
  normalize: true
  useTimestamp: false
  templates:
    enabled: true
    css:
      src: "./templates/_icons-settings.scss.ejs"
      dest: "src/scss/abstract/variables/"
  formats:
    - "ttf"
    - "eot"
    - "woff"
    - "svg"

# SASS
scss:
  enabled: true
  variablesPath: null
  scssPath: "src/scss"
  flattenDestOutput: true
  lint:
    enabled: true
    failOnError: true
    # in addition to linting `css.src`, this is added.
    extraSrc: []
  # enables additional debugging information in the output file as CSS
  # comments - only use when necessary
  sourceComments: false
  sourceMapEmbed: false
  # tell the compiler whether you want "expanded" or "compressed" output code
  outputStyle: "expanded"
  # https://github.com/ai/browserslist#queries
  autoPrefixerBrowsers:
    - "last 2 versions"
    - "IE >= 10"
  includePaths:
    - "./node_modules"

# Copy vendor assets
assets:
  enabled: true
  targetDefaultPath: 'assets/vendor/{name}'
  paths: []
  # examplePaths:
  #   - 'my-library'
  #   -
  #     library: 'vanilla-back-to-top'
  #     name: 'foo' # default to NULL
  #     subPath: 'dist/' # default to ''
  #     target: 'path/other' # default to NULL